name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Docker Login
      uses: docker/login-action@v1.14.1
      with:
        registry: registry.isaacbs.com
        username: ${{ secrets.REG_USERNAME }}
        password: ${{ secrets.REG_PASSWORD }}

    - name: Checkout code
      uses: actions/checkout@v4

    - name: Build Docker image
      run: docker buildx build . --file Dockerfile --tag sam:dev

    - name: Docker tag images
      run: docker tag sam:dev registry.isaacbs.com/sam:dev

    - name: Push Gateway image
      run: docker push registry.isaacbs.com/sam:dev

    - name: Trigger Portainer Webhook
      run: curl -X POST ${{ secrets.PORTAINER_WEBHOOK_URL }}
